eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
        defaultZone: http://localhost:8766/eureka/
        
        
        
app:
  name: aditya maurya is a good 
        
